version: '2'
services:
    postgres:
        image: postgres:alpine
        environment:
            - POSTGRES_USER=reviewboard
    memcached:
        image: memcached:alpine
    reviewboard:
        build: ./reviewboard
        volumes:
            - /root/.ssh
            - /media
        depends_on:
            - postgres
            - memcached
        environment:
            - PGHOST=postgres
            - MEMCACHED=memcached:11211
            - WAIT_FOR_POSTGRES=true
        ports:
            - 8000:8000
    svnserver:
        image: elleflorio/svn-server
        ports:
            - '8080:80'
            - '3960:3960'
            - '4443:443'
    jenkins:
        image: jenkins/jenkins:lts
        ports:
            - '8082:8080'
    webhook:
        build:
            ./webhook
        ports:
            - '8081:8081'
        volumes:
            - './webhook:/webhook'
